name: ElestyaBedrock
version: '${version}'

main: fr.kilian.elestya.ElestyaBedrock
api-version: '1.21.11'
load: POSTWORLD

authors: [ TablePasDroite ]

commands:
  guilde:
    description: show guild menu
    aliases:
      - guildes
  boutique:
    description: show shop menu
    aliases:
      - shop
  menu:
    description: show main menu

depend:
  - Geyser-Spigot
  - floodgate
