name: ElestyaBedrock
version: '${version}'

main: fr.kilian.elestya.ElestyaBedrock
api-version: '1.21.11'
load: POSTWORLD

authors: [ TablePasDroite ]

commands:
  guildmenu:
    description: show form

depend:
  - Geyser-Spigot
  - floodgate
